server:
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: local
  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# Springdoc (Swagger UI)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    display-request-duration: true
    groups-order: ASC

logging:
  level:
    com.easytrax.easytraxbackend: info
