spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    open-in-view: false

logging:
  level:
    com.easytrax.easytraxbackend: info

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${S3_REGION:ap-northeast-2}
    s3:
      bucket: ${S3_BUCKETNAME:easytrax-bucket}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_EXPIRATION}
    header: ${JWT_ACCESS_HEADER:Authorization}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
    header: ${JWT_REFRESH_HEADER:RefreshToken}

oauth:
  kakao:
    audience: ${KAKAO_AUDIENCE}

# Google Gemini API Configuration (Production)
gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash-lite
    base-url: https://generativelanguage.googleapis.com
